name: ex3
on: push

jobs:
  build:
      name: Hello world action
      runs-on: ubuntu-latest
      steps:
         - run: sudo apt-get install -y bats
         - uses: ./erx3
         - run: bats ./erx3/test.sh
        
