name: A workflow for my Hello World file
on: push

jobs:
  build:
      name: Hello world action
      runs-on: ubuntu-latest
      steps:
         - run: sudo apt-get install -y bats
         - uses: actions/checkout@v1
         - uses: ./erx3
           with:
            MY_NAME: "Mona"
