
name: test
on: push

jobs:
  build:
      name: test
      runs-on: ubuntu-latest
      steps:
         - run: sudo apt-get install -y bats
         - uses: actions/checkout@v1
          
         - uses: ./action-a
         - run: ls
         - run: chmod 755 ./action-a/entrypoint.sh
         - run: bats action-a/test.sh
            with: 
              name: aMona
